name: NorbioweZadanieBojowe
version: ${project.version}
main: me.minemis.norbiowezadaniebojowe.NorbioweZadanieBojowe
author: minemis
api-version: 1.12.2
commands:
  showtime:
    description: Shows how much time has passed since Player logged in.
    usage: /showtime
  gitujemy:
    description: Some git test
    usage: /gitujemy